name: Deploy static content to Pages

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - 'feature/**'
  pull_request:
    branches:
    - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-test:
    name: Build Test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Restore NuGet packages
      shell: bash
      run: |
        dotnet restore

    - name: Build solution
      shell: bash
      run: |
        dotnet build -c Release

    - name: Test solution
      shell: bash
      run: |
        dotnet test -c Release

    - name: Update database
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
      shell: bash
      run: |
        cp ./data/*.json ./src/ServerlessDays.WebApp/wwwroot/data/

    - name: Update basepath
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
      shell: pwsh
      run: |
        $content = Get-Content -Path ./src/ServerlessDays.WebApp/wwwroot/index.html
        $content -replace "<base href=`"/`" />", "<base href=`"/serverlessdays-seoul/`" />" | Set-Content -Path ./src/ServerlessDays.WebApp/wwwroot/index.html -Encoding UTF8 -Force

        $content = Get-Content -Path ./src/ServerlessDays.WebApp/wwwroot/data/navigation.json
        $content -replace '"url": "/",', '"url": "/serverlessdays-seoul/",' | Set-Content -Path ./src/ServerlessDays.WebApp/wwwroot/data/navigation.json -Encoding UTF8 -Force

    - name: Publish artifact
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
      shell: bash
      run: |
        dotnet publish -c Release

    - name: Upload artifact
      if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'
      uses: actions/upload-pages-artifact@v1
      with:
        path: src/ServerlessDays.WebApp/bin/Release/net7.0/publish/wwwroot

  deploy:
    name: Deploy to Pages
    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'main'

    needs:
    - build-test

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1